//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle bake <model>` is documented as deferred to a follow-on PRD (PRD-cradle-bake-integration.md). v0.1 returns a clear `not yet implemented in v0.1` error pointing at the follow-on PRD; this is intentional and tested.
//! Test predicate: tests/acceptance_ac8_bake_deferred.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac8() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC8 not yet implemented — see file header");
}
