//! Acceptance test for AC6 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: cradle-harvest ships a `redirect_v1` label extractor that matches positive_keywords from spec.toml against user turns and (when require_behavioral_change_next_turn is true) only emits positives where the next assistant turn shows a behavioral signal (tool use, file edit, or revert keyword). Negative examples are sampled from non-matching user turns.
//! Test predicate: tests/acceptance_ac6_redirect_v1_labels.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac6` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac6() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC6 not yet implemented — see file header");
}
