//! Acceptance test for AC12 (SHOULD) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: Harvest reports per-model summary stats (positive count, negative count, sessions seen, turns scanned) to stderr at the end of the run; stable format suitable for grep + parse.
//! Test predicate: tests/acceptance_ac12_harvest_stats.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac12` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac12() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC12 not yet implemented — see file header");
}
