//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle harvest <model>` reads a model spec.toml, walks a configurable transcripts directory of *.jsonl files, applies the label_extractor named in the spec, and writes data/<model>/{train,val,test}.jsonl. Each output row is JSON with fields {features, label, source_session, source_turn}.
//! Test predicate: tests/acceptance_ac3_harvest_emits_split.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac3() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC3 not yet implemented — see file header");
}
