//! Acceptance test for AC10 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle build <model>` runs harvest -> train in sequence and returns nonzero if any stage fails. Bake stage is skipped in v0.1 with an explicit `phase 2: deferred (see PRD-cradle-bake-integration.md)` notice on stdout.
//! Test predicate: tests/acceptance_ac10_build_orchestration.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac10` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac10() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC10 not yet implemented — see file header");
}
