//! Acceptance test for AC2 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle --help` lists the v0.1 subcommands: harvest, train, bake, build, status. Each prints its own --help. Unknown subcommand returns nonzero with a clap error.
//! Test predicate: tests/acceptance_ac2_cli_help.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac2` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::panic, clippy::missing_panics_doc, clippy::float_cmp, clippy::missing_const_for_fn, clippy::similar_names, clippy::redundant_clone, clippy::option_if_let_else, clippy::needless_collect, clippy::bool_assert_comparison, clippy::large_stack_arrays)]

use std::process::Command;

fn bin() -> std::path::PathBuf {
    let mut p = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("target");
    p.push("debug");
    p.push("cradle");
    p
}

fn ensure_bin_built() {
    let status = Command::new(env!("CARGO"))
        .args(["build", "--bin", "cradle", "--quiet"])
        .status()
        .unwrap();
    assert!(status.success(), "cargo build failed");
}

#[test]
fn acceptance_ac2() {
    ensure_bin_built();
    let exe = bin();
    let out = Command::new(&exe).arg("--help").output().unwrap();
    assert!(out.status.success(), "--help should succeed");
    let s = String::from_utf8_lossy(&out.stdout);
    for sub in ["harvest", "train", "bake", "build", "status"] {
        assert!(s.contains(sub), "--help missing subcommand {sub}: {s}");
    }
    for sub in ["harvest", "train", "bake", "build", "status"] {
        let out = Command::new(&exe).args([sub, "--help"]).output().unwrap();
        assert!(out.status.success(), "{sub} --help should succeed");
    }
    let bad = Command::new(&exe).arg("nope-not-a-subcommand").output().unwrap();
    assert!(!bad.status.success(), "unknown subcommand must be nonzero");
}
