//! Acceptance test for AC9 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle status` prints a one-line-per-model summary of the models/ directory: whether spec.toml is present, whether data/ exists, whether the train step has produced a checkpoint. Output is human-readable text on stdout, machine-readable JSON with --json.
//! Test predicate: tests/acceptance_ac9_status.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac9` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac9() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC9 not yet implemented — see file header");
}
