//! Acceptance test for AC7 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle train <model>` shells out to `uv run python models/<model>/train.py` (or a user-configured runner) with stable env vars CRADLE_MODEL_NAME, CRADLE_DATA_DIR, CRADLE_OUTPUT_DIR. If train.py is missing, cradle returns a clear error. If train.py exits nonzero, cradle returns nonzero with the runner's stderr surfaced. The actual model training is the user's responsibility; v0.1 only orchestrates.
//! Test predicate: tests/acceptance_ac7_train_shellout.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac7` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac7() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC7 not yet implemented — see file header");
}
