//! Acceptance test for AC11 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: Workspace passes `cargo clippy --workspace -- -D warnings` and `cargo deny check bans licenses sources`. (Full `cargo deny check` is avoided because cargo-deny 0.18.3 errors on a CVSS 4.0 advisory; the three-subset form is the documented workaround.)
//! Test predicate: tests/acceptance_ac11_lint_clean.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac11` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac11() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC11 not yet implemented — see file header");
}
