//! Acceptance test for AC8 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: `cradle bake <model>` is documented as deferred to a follow-on PRD (PRD-cradle-bake-integration.md). v0.1 returns a clear `not yet implemented in v0.1` error pointing at the follow-on PRD; this is intentional and tested.
//! Test predicate: tests/acceptance_ac8_bake_deferred.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown, clippy::indexing_slicing, clippy::panic, clippy::missing_panics_doc, clippy::float_cmp, clippy::missing_const_for_fn, clippy::similar_names, clippy::redundant_clone, clippy::option_if_let_else, clippy::needless_collect, clippy::bool_assert_comparison, clippy::large_stack_arrays)]

use cradle::orchestrator::{OrchestrationError, run_bake};

#[test]
fn acceptance_ac8() {
    let err = run_bake("redirect").unwrap_err();
    let msg = err.to_string();
    assert!(matches!(err, OrchestrationError::BakeDeferred));
    assert!(
        msg.contains("PRD-cradle-bake-integration.md"),
        "error must mention the follow-on PRD; got: {msg}"
    );
    assert!(
        msg.contains("not yet implemented in v0.1"),
        "error must mention v0.1 deferral; got: {msg}"
    );
}
