//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: cradle (cli)
//! AC description: The train/val/test split is deterministic and stable: identical inputs produce identical splits across runs. Split is keyed by SHA-256(session_id) mod 100 with holdout_session_fraction (val) and test_session_fraction (test) drawn from spec.toml. The same session never appears in more than one split.
//! Test predicate: tests/acceptance_ac4_split_deterministic.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac4() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC4 not yet implemented — see file header");
}
